old_sound_rabbit_mq:
    connections:
        default:
            host: rabbitmq
            user: rabbitmq
            password: rabbitmq

    consumers:
        insert_queue:
            connection: default
            queue_options:
                name: insert_queue
            callback: InsertEntityConsumer
        update_queue:
            connection: default
            queue_options:
                name: update_queue
            callback: UpdateEntityConsumer
        delete_queue:
            connection: default
            queue_options:
                name: delete_queue
            callback: DeleteEntityConsumer

    multiple_consumers:
        insert_entity_event_queue:
            connection: default
            exchange_options:
                name: insert_entity_event_queue
                type: fanout
            queues:
                insert_entity_event_queue:
                    name: insert_entity_event_queue
                    callback: ReplicateForQueryConsumer




services:

    SymfonyContainer:
        class: Osds\Api\Infrastructure\Bus\SymfonyContainer
        autowire: true
    RabbitMQ:
        class: Osds\Api\Infrastructure\AMQP\RabbitMQ
        arguments:
            - rabbitmq
            - 5672
            - rabbitmq
            - rabbitmq
    Osds\Api\Domain\Bus\Query\QueryBus:
        autowire: true
#        arguments: [ "@SymfonyContainer" ]
    Osds\Api\Domain\Bus\Command\CommandBus:
        autowire: true
#        arguments:
#            - "@SymfonyContainer"

    Illuminate\Http\Request:
        autowire: true
    Elasticsearch\ClientBuilder:
        autowire: true

    #### Insert Entity
    Osds\Api\UI\InsertEntityController:
        autowire: true
        tags: ['controller.service_arguments']
    Osds\Api\Application\Insert\InsertEntityCommandHandler:
        public: true
        arguments:
            - "@InsertEntityUseCase"
            - "@RabbitMQ"
    InsertEntityUseCase:
        class: Osds\Api\Application\Insert\InsertEntityUseCase
        autowire: true
    Osds\Api\Application\Insert\InsertEntityRepository:
        autowire: true
    InsertEntityConsumer:
        class: Osds\Api\Application\Insert\InsertEntityConsumer
        autowire: true


    #### Replicate
    Osds\Api\Application\Replicate\ReplicateForQueryCommandHandler:
        public: true
        arguments:
            - "@ReplicateForQueryUseCase"
    ReplicateForQueryUseCase:
        class: Osds\Api\Application\Replicate\ReplicateForQueryUseCase
        autowire: true
    Osds\Api\Application\Replicate\ReplicateForQueryRepository:
        autowire: true
    ReplicateForQueryConsumer:
        class: Osds\Api\Application\Replicate\ReplicateForQueryConsumer
        autowire: true


    #### Search Entity
    Osds\Api\UI\SearchEntityController:
        autowire: true
        tags: ['controller.service_arguments']
    Osds\Api\Application\Search\SearchEntityQueryHandler:
        public: true
        autowire: true
    Osds\Api\Application\Search\SearchEntityUseCase:
        autowire: true
    Osds\Api\Application\Search\SearchEntityRepository:
        autowire: true


    #### Update Entity
    Osds\Api\UI\UpdateEntityController:
        autowire: true
        tags: ['controller.service_arguments']
    Osds\Api\Application\Update\UpdateEntityCommandHandler:
        public: true
        arguments:
            - "@UpdateEntityUseCase"
            - "@RabbitMQ"
    UpdateEntityUseCase:
        class: Osds\Api\Application\Update\UpdateEntityUseCase
        autowire: true
    Osds\Api\Application\Update\UpdateEntityRepository:
        autowire: true
    UpdateEntityConsumer:
      class: Osds\Api\Application\Update\UpdateEntityConsumer
      autowire: true


    #### Delete Entity
    Osds\Api\UI\DeleteEntityController:
        autowire: true
        tags: ['controller.service_arguments']
    Osds\Api\Application\Delete\DeleteEntityCommandHandler:
        public: true
        arguments:
            - "@DeleteEntityUseCase"
            - "@RabbitMQ"
    DeleteEntityUseCase:
        class: Osds\Api\Application\Delete\DeleteEntityUseCase
        autowire: true
    Osds\Api\Application\Delete\DeleteEntityRepository:
        autowire: true
    DeleteEntityConsumer:
      class: Osds\Api\Application\Delete\DeleteEntityConsumer
      autowire: true

