old_sound_rabbit_mq:
    connections:
        default:
            host: rabbitmq
            user: rabbitmq
            password: rabbitmq

    consumers:
        insert:
            connection: default
            queue_options:
                name: insert
            callback: InsertEntityConsumer
        update:
            connection: default
            queue_options:
                name: update
            callback: UpdateEntityConsumer
        delete:
            connection: default
            queue_options:
                name: delete
            callback: DeleteEntityConsumer

    multiple_consumers:
        insert_completed:
            connection: default
            exchange_options:
                name: insert_completed
                type: fanout
            queues:
                insert_completed_replicate:
                    name: insert_completed
                    callback: ReplicateForQueryConsumer
#                insert_completed_log:
#                    name: insert_completed
#                    callback: LogConsumer
        update_completed:
            connection: default
            exchange_options:
                name: update_completed
                type: fanout
            queues:
                update_completed:
                    name: update_completed
                    callback: ReplicateForQueryConsumer
        delete_completed:
            connection: default
            exchange_options:
                name: delete_completed
                type: fanout
            queues:
                delete_completed:
                    name: delete_completed
                    callback: ReplicateForQueryConsumer


services:

    ###############
    ### Vendors ###
    ###############
    Illuminate\Http\Request:
        autowire: true
    Elasticsearch\ClientBuilder:
        autowire: true

    ### Container for creating handlers on Bus
    SymfonyContainer:
        class: Osds\Api\Infrastructure\Bus\SymfonyContainer
        autowire: true

    RabbitMQ:
        class: Osds\Api\Infrastructure\AMQP\RabbitMQ
        arguments:
            - rabbitmq
            - 5672
            - rabbitmq
            - rabbitmq

    Osds\Api\Domain\Bus\Query\QueryBus:
        arguments:
            - "@SymfonyContainer"
    Osds\Api\Domain\Bus\Command\CommandBus:
        arguments:
            - "@SymfonyContainer"


    ####################
    ### Repositories ###
    ####################
    DoctrineRepository:
        class: Osds\Api\Infrastructure\Repositories\DoctrineRepository
        autowire: true
    ElasticCacheRepository:
        class: Osds\Api\Infrastructure\Repositories\ElasticCacheRepository
        autowire: true


    ##########
    ### UI ###
    ##########
    #### Insert Entity
    Osds\Api\UI\InsertEntityController:
        autowire: true
        tags: ['controller.service_arguments']
    Osds\Api\Application\Insert\InsertEntityCommandHandler:
        public: true
        arguments:
            - "@InsertEntityUseCase"
            - "@RabbitMQ"
    InsertEntityUseCase:
        class: Osds\Api\Application\Insert\InsertEntityUseCase
        autowire: true
    Osds\Api\Application\Insert\InsertEntityRepository:
        public: true
        arguments:
            - "@DoctrineRepository"
    InsertEntityConsumer:
        class: Osds\Api\Application\Insert\InsertEntityConsumer
        autowire: true


    #### Search Entity
    Osds\Api\UI\SearchEntityController:
        autowire: true
        tags: ['controller.service_arguments']
    Osds\Api\Application\Search\SearchEntityQueryHandler:
        public: true
        autowire: true
    Osds\Api\Application\Search\SearchEntityUseCase:
        autowire: true
    Osds\Api\Application\Search\SearchEntityRepository:
        public: true
        arguments:
            - "@ElasticCacheRepository"
#            - "@DoctrineRepository"


    #### Update Entity
    Osds\Api\UI\UpdateEntityController:
        autowire: true
        tags: ['controller.service_arguments']
    Osds\Api\Application\Update\UpdateEntityCommandHandler:
        public: true
        arguments:
            - "@UpdateEntityUseCase"
            - "@RabbitMQ"
    UpdateEntityUseCase:
        class: Osds\Api\Application\Update\UpdateEntityUseCase
        autowire: true
    Osds\Api\Application\Update\UpdateEntityRepository:
        public: true
        arguments:
            - "@DoctrineRepository"
    UpdateEntityConsumer:
      class: Osds\Api\Application\Update\UpdateEntityConsumer
      autowire: true


    #### Delete Entity
    Osds\Api\UI\DeleteEntityController:
        autowire: true
        tags: ['controller.service_arguments']
    Osds\Api\Application\Delete\DeleteEntityCommandHandler:
        public: true
        arguments:
            - "@DeleteEntityUseCase"
            - "@RabbitMQ"
    DeleteEntityUseCase:
        class: Osds\Api\Application\Delete\DeleteEntityUseCase
        autowire: true
    Osds\Api\Application\Delete\DeleteEntityRepository:
        public: true
        arguments:
            - "@DoctrineRepository"
    DeleteEntityConsumer:
      class: Osds\Api\Application\Delete\DeleteEntityConsumer
      autowire: true


    #### Replicate
    ReplicateForQueryConsumer:
        class: Osds\Api\Application\Replicate\ReplicateForQueryConsumer
        autowire: true
    Osds\Api\Application\Replicate\ReplicateForQueryCommandHandler:
        public: true
        autowire: true
    Osds\Api\Application\Replicate\ReplicateForQueryUseCaseFactory:
        public: true
        arguments:
            - "@ElasticCacheRepository"
    LogConsumer:
        class: Osds\Api\Application\Replicate\LogConsumer
        autowire: true