services:
    Illuminate\Http\Request:
        autowire: true


    Osds\Api\Application\Insert\InsertEntityCommandBus:
        autowire: true
    Osds\Api\Application\Insert\InsertEntityCommandHandler:
        autowire: true
    Osds\Api\Application\Insert\InsertEntityUseCase:
        autowire: true
    Osds\Api\Application\Insert\InsertEntityRepository:
        autowire: true
    Osds\Api\UI\InsertEntityController:
        autowire: true
        tags: ['controller.service_arguments']

    Osds\Api\Application\Get\GetEntityQueryBus:
        autowire: true
    Osds\Api\Application\Get\GetEntityQueryHandler:
        autowire: true
    Osds\Api\Application\Get\GetEntityUseCase:
        autowire: true
    Osds\Api\Application\Get\GetEntityRepository:
        autowire: true
    Osds\Api\UI\GetEntityController:
        autowire: true
        tags: ['controller.service_arguments']


    Osds\Api\Application\Delete\DeleteEntityCommandBus:
        autowire: true
    Osds\Api\Application\Delete\DeleteEntityCommandHandler:
        autowire: true
    Osds\Api\Application\Delete\DeleteEntityUseCase:
        autowire: true
    Osds\Api\Application\Delete\DeleteEntityRepository:
        autowire: true
    Osds\Api\UI\DeleteEntityController:
        autowire: true
        tags: ['controller.service_arguments']