services:
    Illuminate\Http\Request:
        autowire: true


    Osds\Api\Application\Insert\InsertEntityCommandBus:
        autowire: true
    Osds\Api\Application\Insert\InsertEntityCommandHandler:
        autowire: true
    Osds\Api\Application\Insert\InsertEntityUseCase:
        autowire: true
    Osds\Api\Application\Insert\InsertEntityRepository:
        autowire: true
    Osds\Api\UI\InsertEntityController:
        autowire: true
        tags: ['controller.service_arguments']

    Osds\Api\Application\Search\SearchEntityQueryBus:
        autowire: true
    Osds\Api\Application\Search\SearchEntityQueryHandler:
        autowire: true
    Osds\Api\Application\Search\SearchEntityUseCase:
        autowire: true
    Osds\Api\Application\Search\SearchEntityRepository:
        autowire: true
    Osds\Api\UI\SearchEntityController:
        autowire: true
        tags: ['controller.service_arguments']


    Osds\Api\Application\Update\UpdateEntityCommandBus:
        autowire: true
    Osds\Api\Application\Update\UpdateEntityCommandHandler:
        autowire: true
    Osds\Api\Application\Update\UpdateEntityUseCase:
        autowire: true
    Osds\Api\Application\Update\UpdateEntityRepository:
        autowire: true
    Osds\Api\UI\UpdateEntityController:
        autowire: true
        tags: ['controller.service_arguments']

    Osds\Api\Application\Delete\DeleteEntityCommandBus:
        autowire: true
    Osds\Api\Application\Delete\DeleteEntityCommandHandler:
        autowire: true
    Osds\Api\Application\Delete\DeleteEntityUseCase:
        autowire: true
    Osds\Api\Application\Delete\DeleteEntityRepository:
        autowire: true
    Osds\Api\UI\DeleteEntityController:
        autowire: true
        tags: ['controller.service_arguments']