services:
    Illuminate\Http\Request:
        autowire: true

    Osds\Api\Infrastructure\Controllers\BaseController:
        autowire: true

    Osds\Api\Infrastructure\Controllers\SymfonyController:
        autowire: true
        tags: ['controller.service_arguments']

    Osds\Api\Infrastructure\Repositories\DoctrineModelRepository:
        autowire: true
        class: App\Infrastructure\Repositories\DoctrineModelRepository
        arguments: ["@doctrine.orm.entity_manager"]