services:

    PSRLogger:
        class: Osds\DDDCommon\Infrastructure\Log\PSRLogger
        arguments:
            - "@Psr\\Log\\LoggerInterface"


monolog:
    handlers:
        # this "file_log" key could be anything
        file_log:
            type: stream
            # log to var/log/(environment).log
            path: "%kernel.logs_dir%/osds_api_%kernel.environment%.log"
            # log *all* messages (debug is lowest level)
            level: info

        syslog_handler:
            type: syslog
            # log error-level messages and higher
            level: error