imports:
    - { resource: RequestParametersForYaml.php }

parameters:

    elk_configuration:
        server: elk

services:
    EntityDoctrineRepository:
        class: Osds\Api\Infrastructure\Persistence\Domain\Entity\EntityDoctrineRepository
        arguments:
            - "@doctrine"
    EntityElasticCacheRepository:
        class: Osds\Api\Infrastructure\Persistence\Domain\Entity\EntityElasticCacheRepository
        arguments:
            - "@Elasticsearch\\ClientBuilder"
            - '%elk_configuration%'
    EntityCsvRepository:
        class: Osds\Api\Infrastructure\Persistence\Domain\Entity\EntityCsvRepository
    EntityInMemoryRepository:
        class: Osds\Api\Infrastructure\Persistence\Domain\Entity\InMemoryRepository