services:

  ##########
  ### UI ###
  ##########

  ### Shared actions
  Osds\Api\UI\Controller\CheckStatusController:
    autowire: true
    tags: ['controller.service_arguments']


  ### AUTH ###
  ### LoginUser
  Osds\Api\UI\Controller\Auth\LoginUserController:
    autowire: true
    arguments:
      - "@Illuminate\\Http\\Request"
      - "@Osds\\Api\\Domain\\Bus\\Query\\QueryBus"
      - "@PSRLogger"
      - "@JWTAuth"
      - "@SymfonyUser"
    tags: ['controller.service_arguments']
  Osds\Api\Application\Auth\LoginUserQueryHandler:
    public: true
    autowire: true
    arguments:
      - "@LoginUserUseCase"
  LoginUserUseCase:
    class: Osds\Api\Application\Auth\LoginUserUseCase
    autowire: true

  #### Insert Entity
  Osds\Api\UI\Controller\InsertEntityController:
    arguments:
      - "@Illuminate\\Http\\Request"
      - "@Osds\\Api\\Domain\\Bus\\Command\\CommandBus"
      - "@PSRLogger"
    tags: ['controller.service_arguments']
  Osds\Api\Application\Insert\InsertEntityCommandHandler:
    public: true
    arguments:
      - "@InsertEntityUseCase"
      - "@RabbitMQ"
  InsertEntityUseCase:
    class: Osds\Api\Application\Insert\InsertEntityUseCase
    public: true
    arguments:
      - "@EntityDoctrineRepository"
  InsertEntityConsumer:
    class: Osds\Api\Application\Insert\InsertEntityConsumer
    arguments:
      - "@Osds\\Api\\Application\\Insert\\InsertEntityCommandHandler"
      - "@PSRLogger"


  #### Search Entity
  Osds\Api\UI\Controller\SearchEntityController:
    autowire: true
    arguments:
      - "@Illuminate\\Http\\Request"
      - "@Osds\\Api\\Domain\\Bus\\Query\\QueryBus"
      - "@PSRLogger"
    tags: ['controller.service_arguments']
  Osds\Api\Application\Search\SearchEntityQueryHandler:
    public: true
    arguments:
      - "@SearchEntityUseCase"
  SearchEntityUseCase:
    class: Osds\Api\Application\Search\SearchEntityUseCase
    public: true
    arguments:
      - "@EntityElasticCacheRepository"
#      - "@EntityDoctrineRepository"



  #### Update Entity
  Osds\Api\UI\Controller\UpdateEntityController:
    public: true
    arguments:
      - "@Illuminate\\Http\\Request"
      - "@Osds\\Api\\Domain\\Bus\\Command\\CommandBus"
    tags: ['controller.service_arguments']
  Osds\Api\Application\Update\UpdateEntityCommandHandler:
    public: true
    arguments:
      - "@UpdateEntityUseCase"
      - "@RabbitMQ"
  UpdateEntityUseCase:
    class: Osds\Api\Application\Update\UpdateEntityUseCase
    public: true
    arguments:
      - "@EntityDoctrineRepository"
  UpdateEntityConsumer:
    class: Osds\Api\Application\Update\UpdateEntityConsumer
    autowire: true


  #### Delete Entity
  Osds\Api\UI\Controller\DeleteEntityController:
    public: true
    arguments:
      - "@Illuminate\\Http\\Request"
      - "@Osds\\Api\\Domain\\Bus\\Command\\CommandBus"
    tags: ['controller.service_arguments']
  Osds\Api\Application\Delete\DeleteEntityCommandHandler:
    public: true
    arguments:
      - "@DeleteEntityUseCase"
      - "@RabbitMQ"
  DeleteEntityUseCase:
    class: Osds\Api\Application\Delete\DeleteEntityUseCase
    public: true
    arguments:
      - "@EntityDoctrineRepository"
  DeleteEntityConsumer:
    class: Osds\Api\Application\Delete\DeleteEntityConsumer
    autowire: true


  #### Replicate
  ReplicateForQueryConsumer:
    class: Osds\Api\Application\Replicate\ReplicateForQueryConsumer
    arguments:
      - "@Osds\\Api\\Domain\\Bus\\Command\\CommandBus"
      - "@PSRLogger"
  Osds\Api\Application\Replicate\ReplicateForQueryCommandHandler:
    public: true
    autowire: true
  Osds\Api\Application\Replicate\ReplicateForQueryUseCaseFactory:
    public: true
    arguments:
      - "@EntityElasticCacheRepository"


  ################
  ### COMMANDS ###
  ################

  ### Command for reloading the ES
  ReloadEntityContentOnQueryRepository:
    tags:
      name: 'console.command'
      command: 'osds:reload-entity-content'
    class: Osds\Api\UI\Command\ReloadEntityContentOnQueryRepositoryCommand
    arguments:
      - "@ReloadEntityContentOnQueryRepositoryQueryHandler"
      - "@Osds\\Api\\Application\\Replicate\\ReplicateForQueryCommandHandler"
  ReloadEntityContentOnQueryRepositoryQueryHandler:
    class: Osds\Api\Application\Search\SearchEntityQueryHandler
    arguments:
      - "@ReloadEntityContentOnQueryRepositoryUseCase"
  ReloadEntityContentOnQueryRepositoryUseCase:
    class: Osds\Api\Application\Search\SearchEntityUseCase
    public: true
    arguments:
      - "@EntityDoctrineRepository"


  LogConsumer:
    class: Osds\Api\Application\Replicate\LogConsumer
    autowire: true