-- MySQL Script generated by MySQL Workbench
-- Sat Feb  9 09:34:49 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog` DEFAULT CHARACTER SET utf8 ;
USE `blog` ;

-- -----------------------------------------------------
-- Table `blog`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`user` ;

CREATE TABLE IF NOT EXISTS `blog`.`user` (
  `uuid` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`uuid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`post` ;

CREATE TABLE IF NOT EXISTS `blog`.`post` (
  `uuid` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NULL,
  `content` MEDIUMTEXT NULL,
  `user_uuid` VARCHAR(255) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`uuid`),
  INDEX `post_user_idx` (`user_uuid` ASC) INVISIBLE,
  CONSTRAINT `post_user`
    FOREIGN KEY (`user_uuid`)
    REFERENCES `blog`.`user` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog`.`comment` ;

CREATE TABLE IF NOT EXISTS `blog`.`comment` (
  `uuid` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NULL,
  `comment` MEDIUMTEXT NULL,
  `post_uuid` VARCHAR(255) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`uuid`),
  INDEX `comment_post_idx` (`post_uuid` ASC) INVISIBLE,
  CONSTRAINT `comment_post`
    FOREIGN KEY (`post_uuid`)
    REFERENCES `blog`.`post` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `blog`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `blog`;
INSERT INTO `blog`.`user` (`uuid`, `name`, `email`, `password`, `created_at`, `updated_at`, `deleted_at`) VALUES ('57720b73-2a0f-420d-9c27-d92224ccebdf', 'xavi', 'xavicx@hotmail.com', '1234', '2019-03-14 15:09:26', '2019-03-14 15:09:26', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `blog`.`post`
-- -----------------------------------------------------
START TRANSACTION;
USE `blog`;
INSERT INTO `blog`.`post` (`uuid`, `title`, `content`, `user_uuid`, `created_at`, `updated_at`, `deleted_at`) VALUES ('c9f429ca-f235-4d6c-bc24-a08454dbb95d', 'First post', 'hello world!', '57720b73-2a0f-420d-9c27-d92224ccebdf', '2019-03-14 15:09:26', '2019-03-14 15:09:26', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `blog`.`comment`
-- -----------------------------------------------------
START TRANSACTION;
USE `blog`;
INSERT INTO `blog`.`comment` (`uuid`, `name`, `comment`, `post_uuid`, `created_at`, `updated_at`, `deleted_at`) VALUES ('5d9ace06-d766-44ab-8001-502a505d1e64', 'commenter name', 'this is my comment', 'c9f429ca-f235-4d6c-bc24-a08454dbb95d', '2019-03-14 15:09:26', '2019-03-14 15:09:26', NULL);

COMMIT;

